### ISSUE TITLE
Adicionar cabeçalhos nas requisicoes 

### ISSUE THREAD

**Issue by thenicolau** [DesignLiquido/delegua-http#2]
Os cabeçalhos não estão presentes para ser passado nas requisições

**Comment by thenicolau** [comment]
os cabeçalhos estão presente no momento de criar o clienteHttp, mas da menos flexibilidade em outras rotas caso tenha um cabeçalho diferente

**Comment by thenicolau** [comment]
#4 PR Aberta

**Comment by leonelsanchesdasilva** [comment]
https://github.com/DesignLiquido/delegua-http/pull/4
